// ServicePage.js
import React from 'react';
import { Card, CardContent, Typography, Grid } from '@mui/material';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import BusinessCenterIcon from '@mui/icons-material/BusinessCenter';
import BuildIcon from '@mui/icons-material/Build';
import { motion } from 'framer-motion';
import sliderImage from '../Assets/ipm.jpg';
import anotherImage from '../Assets/so.png';
import printer from '../Assets/ele.jpg';
import printer1 from '../Assets/plu.jpg';
import TrendingLaptops from '../TrendingLaptops/TrendingLaptops';
import './Service.css';

function ServicePage() {
  const services = [
    {
      title: "Annual Maintenance Service (AMC)",
      // icon: <BuildIcon className="service-icon" />,
      items: ["Networking", "Firewall", "WiFi Services", "Biometric & CCTV", "Projector, Printer & Billing", "Desktop & Laptops"]
    },
    {
      title: "HRMS - Manpower",
      // icon: <BusinessCenterIcon className="service-icon" />,
      items: ["Labour Category", "IT Engineers", "Non - IT Employee", "Technician", "Receptionist Manpower"]
    },
    {
      title: "Sales, Service & Rental",
      // icon: <BusinessCenterIcon className="service-icon" />,
      items: ["OS Installation", "Software Development", "PC Building", "Data Recovery", "Other IT Gadgets", "Implied Warranty"]
    }
  ];

  const imageAnimation = {
    hidden: { opacity: 0, x: -50 },
    visible: { opacity: 1, x: 0, transition: { duration: 0.5 } }
  };

  return (
    <div className="service-page">
      <h1 className="main-title">Service</h1>
      <Grid container spacing={4} justifyContent="center">
  {services.map((service, index) => (
    <Grid item xs={12} sm={6} md={3} key={index}> {/* Reduced size on medium and up */}
      <Card className="service-box">
        <CardContent>
          <div className="service-box-header">
            {service.icon}
            <Typography variant="h6" className="service-title">
              {service.title}
            </Typography>
          </div>
          <Grid container spacing={1} className="service-list">
            {service.items.map((item, i) => (
              <Grid item xs={12} key={i} className="service-item">
                <CheckCircleIcon className="item-icon" /> {item}
              </Grid>
            ))}
          </Grid>
        </CardContent>
      </Card>
    </Grid>
  ))}
</Grid>

      <section className="container my-5">
        <div className="row">
          <motion.div className="col-md-6" initial="hidden" whileInView="visible" viewport={{ once: true }} variants={imageAnimation}>
          <div data-aos="fade-right">
  <img 
    src={sliderImage} 
    className="img-fluid rounded shadow" 
    height="60px" 
    width="60%" 
    alt="Product" 
    data-aos="fade-up" 
    data-aos-duration="3000" 
  />
</div>
          </motion.div>
          <div className="col-md-6 d-flex flex-column justify-content-center">
            <h1>EPBX & IP PBX</h1>
            <hr className="section-divider"/>
            <p className="lead"></p>
            <p>Efficient and flexible communication for modern businesses. Easily manage calls within your organization with high-quality IP-PBX technology.</p>
            <p>Ensure seamless connectivity with scalable IP-PBX systems. Ideal for small to large enterprises with varied communication needs.</p>
            <p>Improve communication with IP-PBX technology that supports multiple devices, including desk phones and wireless handsets.</p>
          </div>
        </div>
      </section>

      <section className="container my-5">
        <div className="row">
          <div className="col-md-6 d-flex flex-column justify-content-center">
            <h1>Solar Panel, Inverter & Batteries</h1>
            <hr className="section-divider"/>
          <p>The image displays a comprehensive solar power setup, including solar panels, a battery, an inverter, and a charge controller, ideal for both residential and commercial applications.</p>
          <p>A durable, high-capacity battery ensures that energy generated by the solar panels is stored for continuous use, even during cloudy days or nighttime.</p>
          <p>The inverter in the system converts DC energy from the solar panels and battery into AC power, making it compatible with household and commercial appliance</p>
          </div>
          <motion.div className="col-md-6" initial="hidden" whileInView="visible" viewport={{ once: true }} variants={imageAnimation}>
            <div data-aos="fade-left">
              <img src={anotherImage} className="img-fluid rounded shadow" height="60px" width="60%" alt="New Product"/>
            </div>
          </motion.div>
        </div>
      </section>
       <section className="container my-5">
        <div className="row">
          <motion.div className="col-md-6" initial="hidden" whileInView="visible" viewport={{ once: true }} variants={imageAnimation}>
            <div data-aos="fade-right">
              <img src={printer} className="img-fluid rounded shadow" height="60px" width="60%" alt="Printer Product"/>
            </div>
          </motion.div>
            <div className="col-md-6 d-flex flex-column justify-content-center">
            <h1>Home & Industrial Electrical Work</h1>
            <hr className="section-divider"/>         
            <p>Electrical work is essential for powering homes and industries safely and reliably.</p>
            <p>Services include wiring, lighting, power distribution, and troubleshooting, customized for residential and industrial needs.</p>
            <p>Following safety measures and regulations prevents accidents and ensures safe electrical installations.</p>
            <p>Modern technology, like smart systems and renewable energy, enhances functionality and promotes sustainability.</p>
          </div>
        </div>
      </section>
      <section className="container my-5">
        <div className="row">
          <div className="col-md-6 d-flex flex-column justify-content-center">
            <h1>Plumbing Work</h1>
            <hr className="section-divider"/>
            <p>Plumbing is essential for providing water supply, drainage, and sanitation systems in homes and buildings.</p>
            <p>Plumbing services include pipe installation, leak repairs, drainage solutions, and maintenance of water systems.</p>
            <p>Regular plumbing maintenance helps prevent leaks, clogs, and costly repairs, ensuring efficient water flow and hygiene.</p>
            <p>Following safety guidelines and local plumbing codes is crucial to avoid water contamination and ensure safe installations.</p>
          </div>
          <motion.div className="col-md-6" initial="hidden" whileInView="visible" viewport={{ once: true }} variants={imageAnimation}>
          <div data-aos="zoom-in-left">
          <img src={printer1} className="img-fluid rounded shadow" height="60px" width="60%" alt="New Product"/>
          </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
export default ServicePage;
